fix path to jetty-realm.properties
Where does '../null/' come from?

error message on mvn jetty:start

[ERROR] Failed to execute goal
org.eclipse.jetty:jetty-maven-plugin:11.0.8:run (default-cli)
on project sample11-webapp: Error starting jetty:
InvocationTargetException: Config does not exist:
file:///C:/projects/sample11/sample11-webapp/null/src/etc
/jetty-realm.properties